### ISSUE TITLE
npx zenn preview でエラーが大量に吐き出される

### ISSUE THREAD

**Issue by skanehira** [zenn-dev/zenn-roadmap#37]
## 事象
`"zenn-cli": "^0.1.27"` にアップデートしたら、`npx zenn preview`で大量なエラーが測れるようになった。
ただ、プレビュー自体は動くが、hot reload は動作しない模様。

<details>
<summary>エラーログ</summary>
(node:21013) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/pnp-webpack-plugin/fixtures/file.js'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1329:11)
    at createFsWatchInstance (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:628:21)
(node:21013) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21013) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:21013) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/pnp-webpack-plugin/fixtures/index.js'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1329:11)
    at createFsWatchInstance (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:628:21)
(node:21013) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:21013) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/postcss/docs/architecture.md'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1329:11)
    at createFsWatchInstance (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:628:21)
(node:21013) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:21013) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/postcss/docs/source-maps.md'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1329:11)
    at createFsWatchInstance (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/home/skanehira/dev/go/src/github.com/skanehira/zenn-dev/node_modules/chokidar/lib/nodefs-handler.js:628:21)
(node:21013) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
....
</details>

## 環境
OS：Ubuntu 18.04 LTS
npm: 6.14.8
node: v12.14.0

## 試したこと
- node_modules を削除して再度 npm install したが変わらず
- `^0.1.22`に戻したら問題なくエラーは発生しなかった

**Comment by catnose99** [comment]
ご報告ありがとうございます。
たびたびで申し訳ないのですが、新しいバージョン（`^0.1.27`）をインストールしてみていただけますか？

**Comment by skanehira** [comment]
動きました！
ありがとうございましたm(_ _)m

**Comment by catnose99** [comment]
早速ありがとうございます！🙏🙏🙏
